[dependencies]
base = "0.11.1"
"encoding.mo" = "https://github.com/aviate-labs/encoding.mo#master@2711d18727e954b11afc0d37945608512b5fbce2"
account-identifier = "1.0.2"
map = "9.0.1"
vector = "0.3.1"
StableBuffer = "https://github.com/canscale/StableBuffer#v1.3.0@acdde6bb5b939227997cebdbb8919d2e6da8691c"
ic = "2.1.0"
